exports.PAYMENT_DIRECTION = {
    SENDING_RIPPLE: 0,
    RECEIVING_RIPPLE: 1
};

exports.CONVERSION_DIRECTION = {
    RIPPLE_PER_OTHER_COIN: 0,
    OTHER_COIN_PER_RIPPLE: 1
};

exports.ACTIONS = {
    WITHDRAW: 0,
    DEPOSIT: 1
};